[package]
name = "loadtest-populate"
version = "0.1.0"
edition = "2021"
description = "Common types and utilities for loadtest populators"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
